openapi: '3.0.0'
info:
  version: 1.0.0
  title: jsonviewer.ai Documentation
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /json:
    get:
      summary: List JSON items
      operationId: listJsonItems
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: An paged array of JSON items
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JsonItems'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create JSON item
      operationId: createJsonItem
      responses:
        201:
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /json/{jsonId}:
    get:
      summary: Get JSON item
      operationId: showJsonItemById
      parameters:
        - name: jsonId
          in: path
          required: true
          description: The id of the JSON item to retrieve
          schema:
            type: string
      responses:
        200:
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JsonItems'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /beautify:
    get:
      summary: List beautified JSON
      operationId: listBeautifiedJson
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: A paged array of beautified JSON items
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JsonItems'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Beautify JSON data
      operationId: beautifyJsonData
      responses:
        201:
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    JsonItem:
      required:
        - id
        - content
      properties:
        id:
          type: integer
          format: int64
        content:
          type: string
        status:
          type: string
    JsonItems:
      type: array
      items:
        $ref: '#/components/schemas/JsonItem'
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string